### ISSUE TITLE
Assertion Error when loading the cityscapes dataset

### ISSUE THREAD

**Issue by ankur-chr** [bowenc0221/panoptic-deeplab#117]
I am getting the following error when the code tries to load the cityscapes dataset.  Tried debugging this, but can't solve it.
(running this on a conda based environment on a windows machine)

Traceback (most recent call last):
  File "tools/train_net.py", line 193, in <module>
    main()
  File "tools/train_net.py", line 88, in main
    data_loader = build_train_loader_from_cfg(config)
  File "D:\Masters\dissertation\src\pdl\panoptic-deeplab\tools\..\segmentation\data\build.py", line 113, in build_train_loader_from_cfg
    dataset = build_dataset_from_cfg(config, is_train=True)
  File "D:\Masters\dissertation\src\pdl\panoptic-deeplab\tools\..\segmentation\data\build.py", line 83, in build_dataset_from_cfg
    dataset = dataset_map[config.DATASET.DATASET](
  File "D:\Masters\dissertation\src\pdl\panoptic-deeplab\tools\..\segmentation\data\datasets\cityscapes_panoptic.py", line 65, in __init__
    super(CityscapesPanoptic, self).__init__(root, split, is_train, crop_size, mirror, min_scale, max_scale,
  File "D:\Masters\dissertation\src\pdl\panoptic-deeplab\tools\..\segmentation\data\datasets\cityscapes.py", line 84, in __init__
    assert len(self) == _CITYSCAPES_INFORMATION.splits_to_sizes[self.split]
AssertionError

**Comment by ankur-chr** [comment]
Looks like this issue was due to missing leftImg8bit folder and content. Solved it!

**Comment by ankur-chr** [comment]
Solved
