### ISSUE TITLE
Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by coranholmes** [bowenc0221/panoptic-deeplab#15]
I am running the codes on Windows 10 + cuda 10.1 + pytorch 1.4.0
I have installed `cityscapesScripts` via pip as indicated in your instructions and use the `csCreatePanopticImgs.exe` provided in the scripts to generate the panoptic images. When I try to run 
```
python tools/train_net.py --cfg configs/Base-Panoptic-DeepLab.yaml
```
I have removed `.module` according to your suggestions at #7 but I have got the following new errors. Could you please provide some insights on how to solve this issue? 
```
[32m[06/30 17:02:31 seg.data.build]: [0mUsing training sampler TrainingSampler
[4m[5m[31mERROR[0m [32m[06/30 17:02:38 segmentation]: [0mException during training:
Traceback (most recent call last):
  File "tools/train_net.py", line 139, in main
    out_dict = model(image, data)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\meta_arch\base.py", line 54, in forward
    features = self.backbone(x)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 229, in forward
    return self._forward_impl(x)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 208, in _forward_impl
    x = self.conv1(x)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
[32m[06/30 17:02:38 segmentation]: [0mTraining finished.
Traceback (most recent call last):
  File "tools/train_net.py", line 190, in <module>
    main()
  File "tools/train_net.py", line 139, in main
    out_dict = model(image, data)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\meta_arch\base.py", line 54, in forward
    features = self.backbone(x)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 229, in forward
    return self._forward_impl(x)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 208, in _forward_impl
    x = self.conv1(x)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

**Comment by coranholmes** [comment]
It seems pytorch cannot support multi gpus on Windows well. Is there a way that I can run the codes not using the distributed module?

**Comment by bowenc0221** [comment]
Pull request #9 should solve this problem. The reason it has this error is that the input is on CPU, you should manually copy input to GPU (e.g. input.cuda()) if not using distributed data parallel.

**Comment by coranholmes** [comment]
thank you! Somehow I did not clone the latest codes, #9 does fix this issue.
