### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by coranholmes** [bowenc0221/panoptic-deeplab#16]
Hi, thank you for the awesome work!
I am running the codes on Windows 10 + cuda 10.1 + pytorch1.4.0 with 2080Ti (11G).
When I run the command
```
python tools/train_net.py --cfg configs/Base-Panoptic-DeepLab.yaml
```
I have got the following errors
```
Traceback (most recent call last):
  File "tools/train_net.py", line 143, in main
    out_dict = model(image, data)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\meta_arch\base.py", line 54, in forward
    features = self.backbone(x)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 229, in forward
    return self._forward_impl(x)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 217, in _forward_impl
    x = self.layer2(x)  # 1/8
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\backbone\resnet.py", line 120, in forward
    identity = self.downsample(x)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 260.00 MiB (GPU 0; 11.00 GiB total capacity; 8.10 GiB already allocated; 70.59 MiB free; 8.37 GiB reserved in total by PyTorch)
```
However, I have just restarted the PC and not running other GPU related tasks
```
(deeplab) D:\PyProjects\panoptic-deeplab>nvidia-smi
Wed Jul 01 09:50:11 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 445.75       Driver Version: 445.75       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208... WDDM  | 00000000:21:00.0  On |                  N/A |
|  0%   49C    P8    19W / 300W |    510MiB / 11264MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208... WDDM  | 00000000:4B:00.0 Off |                  N/A |
|  0%   44C    P8    24W / 300W |    215MiB / 11264MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1760    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      1768    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      1800    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      7904    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      9524    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     10816    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     11232    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
|    0   N/A  N/A     12064    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     12368    C+G   ...es.TextInput.InputApp.exe    N/A      |
|    0   N/A  N/A     14828    C+G   ...qxf38zg5c\Skype\Skype.exe    N/A      |
+-----------------------------------------------------------------------------+
```
I am sorry I am a newbie to this. Could you please provide some advice?

**Comment by bowenc0221** [comment]
You can use `configs/panoptic_deeplab_R50_os32_cityscapes.yaml`, but need to change it to:
```
TRAIN:
  IMS_PER_BATCH: 1
GPUS: (0, )
```
You may also need to freeze BN by yourself in this case (freeze BN is not supported in this code yet).

**Comment by coranholmes** [comment]
> 
> 
> You can use `configs/panoptic_deeplab_R50_os32_cityscapes.yaml`, but need to change it to:
> 
> ```
> TRAIN:
>   IMS_PER_BATCH: 1
> GPUS: (0, )
> ```
> 
> You may also need to freeze BN by yourself in this case (freeze BN is not supported in this code yet).

Hi, thank you very much for your prompt reply. I have changed the config file according to your suggestion but have got a new error:
```
[4m[5m[31mERROR[0m [32m[07/01 10:33:34 segmentation]: [0mException during training:
Traceback (most recent call last):
  File "tools/train_net.py", line 143, in main
    out_dict = model(image, data)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\meta_arch\base.py", line 61, in forward
    return self.loss(results, targets)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\meta_arch\panopitc_deeplab.py", line 102, in loss
    results['semantic'], targets['semantic'], semantic_weights=targets['semantic_weights']
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\PyProjects\panoptic-deeplab\tools\..\segmentation\model\loss\criterion.py", line 103, in forward
    pixel_losses = self.criterion(logits, labels) * kwargs['semantic_weights']
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\modules\loss.py", line 932, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\functional.py", line 2317, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\ProgramData\Anaconda3\envs\deeplab\lib\site-packages\torch\nn\functional.py", line 2117, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss2d_forward
```

**Comment by bowenc0221** [comment]
I don't have problem running on my machine (Linux) using the command: `python tools/train_net.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml TRAIN.IMS_PER_BATCH 1 GPUS '(0, )' OUTPUT_DIR ./output/debug`
