### ISSUE TITLE
ModuleNotFoundError: No module named 'panopticapi'

### ISSUE THREAD

**Issue by xyry** [bowenc0221/panoptic-deeplab#49]
When I run this code
```
 python train_panoptic_deeplab.py --config-file config/Cityscapes-PanopticSegmentation/panoptic_deeplab_X_65_os16_mg124_poly_90k_bs32_crop_512_1024.yaml --num-gpus 1

```
The error is like this, can anyone help me?
```
python train_panoptic_deeplab.py --config-file config/Cityscapes-PanopticSegmentation/panoptic_deeplab_X_65_os16_mg124_poly_90k_bs32_crop_512_1024.yaml --num-gpus 1
Traceback (most recent call last):
  File "train_panoptic_deeplab.py", line 28, in <module>
    from detectron2.projects.panoptic_deeplab import (
  File "/mnt/tecmint/data/ypl_file/panoptic-deeplab/panoptic-deeplab-master/tools_d2/detectron2/projects/Panoptic-DeepLab/panoptic_deeplab/__init__.py", line 3, in <module>
    from .dataset_mapper import PanopticDeeplabDatasetMapper
  File "/mnt/tecmint/data/ypl_file/panoptic-deeplab/panoptic-deeplab-master/tools_d2/detectron2/projects/Panoptic-DeepLab/panoptic_deeplab/dataset_mapper.py", line 7, in <module>
    from panopticapi.utils import rgb2id
ModuleNotFoundError: No module named 'panopticapi'
```

**Comment by bowenc0221** [comment]
You will need to install `panopticapi` by: `pip install git+https://github.com/cocodataset/panopticapi.git`

**Comment by xyry** [comment]
Thank you so much, it works!
